version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iot-led"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c1gdh4pvkrqp"
s3_prefix = "iot-led"
region = "eu-west-1"
profile = "gen-sandbox"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
