AWSTemplateFormatVersion: 2010-09-09
Description: >-
  iot-led

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            Auth:
              ApiKeyRequired: true

  getLatestItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-latest-item.getLatestItemHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /latest
            Method: GET
            Auth:
              ApiKeyRequired: true

  getLatestItemMorseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-latest-item-morse.getLatestItemMorseHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /latest/morse
            Method: GET
            Auth:
              ApiKeyRequired: true

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            Auth:
              ApiKeyRequired: true

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  putItemMorseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item-morse.putItemMorseHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StreamTable
      Environment:
        Variables:
          STREAM_TABLE: !Ref StreamTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /morse
            Method: POST

  StreamTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "created_at"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "created_at"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: "myGSI"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
            - AttributeName: "created_at"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "m"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
